[package]
name = "yarrbot"
version = "0.1.0"
edition = "2018"

[workspace]
members = [
    "crates/db",
    "crates/webhook_api",
    "crates/common"
]

[dependencies]
dotenv = "0.15.0"
anyhow = "1.0.42"
actix-web = "3"
log = "0.4"
env_logger = "0.8"
yarrbot_db = { path = "crates/db" }
yarrbot_webhook_api = { path = "crates/webhook_api" }
